services:
  ishauditcore:
    image: ishauditcore
    build:
      context: .
      dockerfile: ISHAuditCore/Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  ishauditapi:
    image: ishauditapi
    build:
      context: .
      dockerfile: ISHAuditAPI/Dockerfile
