// <auto-generated />
using System;
using ISHAuditCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISHAuditCore.Migrations
{
    [DbContext(typeof(ISHAuditDbcontext))]
    [Migration("20240913080845_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ISHAuditCore.Migrations.KpiDocument", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("classname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("file_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("model")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("model_type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("org")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("org_id")
                        .HasColumnType("int");

                    b.Property<string>("parent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("text")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id")
                        .HasName("PK__KpiDocum__3213E83FB0A232F5");

                    b.ToTable("KpiDocument");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_basic_info", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("audit_cause_id")
                        .HasColumnType("int");

                    b.Property<int?>("audit_type_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("disater_types")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("disater_types_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("factory_id")
                        .HasColumnType("int");

                    b.Property<string>("improve_status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal?>("improve_status_val")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("incident_datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("incident_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("participate_status_val")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("penalty")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("penalty_detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sd")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("situation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id")
                        .HasName("PK__audit_ba__3213E83F08EA89FE");

                    b.ToTable("audit_basic_info");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_cause", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cause_code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("cause_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id")
                        .HasName("PK__audit_ca__3213E83F8C3921EA");

                    b.ToTable("audit_cause");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_contact_info", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime");

                    b.Property<int?>("enterprise_id")
                        .HasColumnType("int");

                    b.Property<int?>("factory_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<string>("user_department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("user_job_title")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("user_mail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("user_name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("user_phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id")
                        .HasName("PK__audit_co__3213E83F98B0F683");

                    b.ToTable("audit_contact_info");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_control_yuan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("audit_basic_id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("back_date")
                        .HasColumnType("date");

                    b.Property<string>("back_doc_text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("back_doc_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("back_doc_uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("come_date")
                        .HasColumnType("date");

                    b.Property<string>("come_doc_text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("come_doc_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("come_doc_uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK__audit_co__3213E83F988A5EF1");

                    b.ToTable("audit_control_yuan");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_data_edit", b =>
                {
                    b.Property<string>("uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("audit_uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("end_time")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("start_time")
                        .HasColumnType("datetime");

                    b.Property<string>("status")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("user_contacts")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("uuid")
                        .HasName("PK__audit_da__7F42793084E1BF3B");

                    b.ToTable("audit_data_edit");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_data_edit_log", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("audit_data_edit_uuid")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("improve_status_val")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("participate_status_val")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__audit_da__3213E83F7FE17571");

                    b.ToTable("audit_data_edit_log");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_date", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly?>("audit_date1")
                        .HasColumnType("date")
                        .HasColumnName("audit_date");

                    b.Property<int>("audit_detail_id")
                        .HasColumnType("int");

                    b.Property<string>("due")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id")
                        .HasName("PK__audit_da__3213E83F9A63B9BB");

                    b.ToTable("audit_date");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_detail_info", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("audit_basic_id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("audit_end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("audit_start_date")
                        .HasColumnType("date");

                    b.Property<int?>("enter_type_id")
                        .HasColumnType("int");

                    b.Property<string>("filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("filename_uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("meeting_type_id")
                        .HasColumnType("int");

                    b.Property<string>("reportname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reportname_uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id")
                        .HasName("PK__audit_de__3213E83F68DEFB5B");

                    b.ToTable("audit_detail_info");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_improvement_doc", b =>
                {
                    b.Property<string>("uuid")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("audit_basic_id")
                        .HasColumnType("int");

                    b.Property<string>("doc_text")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("doc_type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("doc_uuid")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("receive_date")
                        .HasColumnType("date");

                    b.HasKey("uuid")
                        .HasName("PK__audit_im__7F427930A24FACEE");

                    b.ToTable("audit_improvement_doc");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_report_commit", b =>
                {
                    b.Property<string>("filename")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("auditData_edit_uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("filetype")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("original_filename")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("filename")
                        .HasName("PK__audit_re__7F42793074DBCE1E");

                    b.ToTable("audit_report_commit");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_report_file_log", b =>
                {
                    b.Property<string>("uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("audit_detail_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("filename")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("filetype")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("uuid")
                        .HasName("PK__audit_re__7F427930CBD00B9B");

                    b.ToTable("audit_report_file_log");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_response_file_log", b =>
                {
                    b.Property<string>("uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("audit_detail_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("filename")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("filetype")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("uuid")
                        .HasName("PK__audit_re__7F42793077BC87F5");

                    b.ToTable("audit_response_file_log");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_suggest", b =>
                {
                    b.Property<string>("uuid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mid_term")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("audit_basic_id")
                        .HasColumnType("int");

                    b.Property<int?>("audit_detail_id")
                        .HasColumnType("int");

                    b.Property<string>("budget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("budget_val")
                        .HasColumnType("int");

                    b.Property<DateTime?>("create_by")
                        .HasColumnType("datetime");

                    b.Property<int?>("expert_id")
                        .HasColumnType("int");

                    b.Property<string>("handling_situation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("improve_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("item_no")
                        .HasColumnType("int");

                    b.Property<string>("long_term")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int");

                    b.Property<string>("participate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsible_unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("short_term")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sub_suggest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("suggest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("suggest_item_id")
                        .HasColumnType("int");

                    b.HasKey("uuid")
                        .HasName("PK__audit_su__7F427930BEA72FCA");

                    b.ToTable("audit_suggest");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.audit_type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("audit_type1")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("audit_type");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__audit_ty__3213E83F53D77E43");

                    b.ToTable("audit_type");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.city_info", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("city")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__city_inf__3213E83F86F45047");

                    b.ToTable("city_info");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.company_name", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("company")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("enterprise_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__company___3213E83FD2C8FC45");

                    b.ToTable("company_name");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.credential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Descriptor")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SignatureCounter")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__credenti__3214EC07E795DAF5");

                    b.HasIndex("UserId");

                    b.ToTable("credentials");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.disaster_type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("disaster")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__disaster__3213E83F175B7130");

                    b.ToTable("disaster_type");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.eco_kpi_datum", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("annual_average")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("annual_average_unit")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("baseline")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("baseline_unit")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("checkout_time")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("checkout_time_unit")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<string>("conform")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("deviation")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("eco_kpi_report_id")
                        .HasColumnType("int");

                    b.Property<int?>("eco_kpi_sub_item_id")
                        .HasColumnType("int");

                    b.Property<int?>("eco_kpi_template_id")
                        .HasColumnType("int");

                    b.Property<string>("execution_of_kpi")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("expressions")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("number")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("objective")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("objective_unit")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK__eco_kpi___3213E83F1A66B86A");

                    b.ToTable("eco_kpi_data");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.eco_kpi_item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("eco_kpi_items")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("number")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK__eco_kpi___3213E83F609D7504");

                    b.ToTable("eco_kpi_item");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.eco_kpi_report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("eco_kpi_report_year")
                        .HasColumnType("int");

                    b.Property<DateTime?>("report_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("id")
                        .HasName("PK__eco_kpi___3213E83F1A438166");

                    b.ToTable("eco_kpi_report");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.eco_kpi_sub_item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("deadline")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("eco_kpi_items_id")
                        .HasColumnType("int");

                    b.Property<string>("eco_kpi_sub_items")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id")
                        .HasName("PK__eco_kpi___3213E83F4B48E634");

                    b.ToTable("eco_kpi_sub_item");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.eco_kpi_template", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("annual_average")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("annual_average_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("baseline")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("baseline_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("checkout_time")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("checkout_time_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("company_name_id")
                        .HasColumnType("int");

                    b.Property<string>("deviation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("eco_kpi_sub_item_id")
                        .HasColumnType("int");

                    b.Property<string>("expressions")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("objective")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("objective_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id")
                        .HasName("PK__eco_kpi___3213E83F01BFB214");

                    b.ToTable("eco_kpi_template");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.enter_type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("enter_type1")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("enter_type");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__enter_ty__3213E83FCBAB158F");

                    b.ToTable("enter_type");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.enterprise_name", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("enterprise")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PK__enterpri__3213E83FDA8300E8");

                    b.ToTable("enterprise_name");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.ep_kpi_datum", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("annual_average")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("annual_average_unit")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("baseline")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("baseline_unit")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("checkout_time")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("checkout_time_unit")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<string>("conform")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("deviation")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ep_kpi_report_id")
                        .HasColumnType("int");

                    b.Property<int?>("ep_kpi_sub_item_id")
                        .HasColumnType("int");

                    b.Property<int?>("ep_kpi_template_id")
                        .HasColumnType("int");

                    b.Property<string>("execution_of_kpi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("execution_of_kpi_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("expressions")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("factory_id")
                        .HasColumnType("int");

                    b.Property<string>("number")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("objective")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("objective_unit")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK__ep_kpi_d__3213E83FDD915878");

                    b.ToTable("ep_kpi_data");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.ep_kpi_item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ep_kpi_items")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("number")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK__ep_kpi_i__3213E83F2E24E921");

                    b.ToTable("ep_kpi_item");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.ep_kpi_report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ep_kpi_report_year")
                        .HasColumnType("int");

                    b.Property<int?>("factory_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("report_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("id")
                        .HasName("PK__ep_kpi_r__3213E83F5999606C");

                    b.ToTable("ep_kpi_report");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.ep_kpi_sub_item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("deadline")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ep_kpi_items_id")
                        .HasColumnType("int");

                    b.Property<string>("ep_kpi_sub_items")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id")
                        .HasName("PK__ep_kpi_s__3213E83FC72ADFEE");

                    b.ToTable("ep_kpi_sub_item");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.ep_kpi_template", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("annual_average")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("annual_average_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("baseline")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("baseline_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("checkout_time")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("checkout_time_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("company_name_id")
                        .HasColumnType("int");

                    b.Property<string>("deviation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ep_kpi_sub_item_id")
                        .HasColumnType("int");

                    b.Property<string>("expressions")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("factory_name_id")
                        .HasColumnType("int");

                    b.Property<string>("objective")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("objective_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id")
                        .HasName("PK__ep_kpi_t__3213E83F4A53ACF5");

                    b.ToTable("ep_kpi_template");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.expert_datum", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("experience")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("expert_names")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("phone_number")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("position_id")
                        .HasColumnType("int");

                    b.Property<string>("remark")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("sevice_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("speciality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("speciality_category")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("tel_number")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("uuid")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("id")
                        .HasName("PK__expert_d__3213E83FF72C1A09");

                    b.ToTable("expert_data");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.factory_name", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("factory")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("industrial_area_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__factory___3213E83FB91AFE5C");

                    b.ToTable("factory_name");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.industrial_area_info", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("industrial_area")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("township_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__industri__3213E83F90524761");

                    b.ToTable("industrial_area_info");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.psm_kpi_datum", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("annual_average")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("annual_average_unit")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("baseline")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("baseline_unit")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("checkout_time")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("checkout_time_unit")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<string>("conform")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("deviation")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("execution_of_kpi")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("expressions")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("factory_id")
                        .HasColumnType("int");

                    b.Property<string>("number")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("objective")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("objective_unit")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("psm_kpi_report_id")
                        .HasColumnType("int");

                    b.Property<int?>("psm_kpi_sub_item_id")
                        .HasColumnType("int");

                    b.Property<int?>("psm_kpi_template_id")
                        .HasColumnType("int");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK__psm_kpi___3213E83F071A7ADA");

                    b.ToTable("psm_kpi_data");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.psm_kpi_item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("number")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("psm_kpi_items")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id")
                        .HasName("PK__psm_kpi___3213E83F3433DA4A");

                    b.ToTable("psm_kpi_item");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.psm_kpi_report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("factory_id")
                        .HasColumnType("int");

                    b.Property<int?>("kpi_report_year")
                        .HasColumnType("int");

                    b.Property<DateTime?>("report_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("id")
                        .HasName("PK__psm_kpi___3213E83F1D396739");

                    b.ToTable("psm_kpi_report");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.psm_kpi_sub_item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("deadline")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("kpi_items_id")
                        .HasColumnType("int");

                    b.Property<string>("kpi_sub_items")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id")
                        .HasName("PK__psm_kpi___3213E83F0A262AA3");

                    b.ToTable("psm_kpi_sub_item");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.psm_kpi_template", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("annual_average")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("annual_average_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("baseline")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("baseline_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("checkout_time")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("checkout_time_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("company_name_id")
                        .HasColumnType("int");

                    b.Property<string>("deviation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("expressions")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("factory_name_id")
                        .HasColumnType("int");

                    b.Property<string>("objective")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("objective_unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("psm_kpi_sub_item_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__psm_kpi___3213E83F20125115");

                    b.ToTable("psm_kpi_template");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.result_datum", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("completion_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("enterprise_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("estimated_completion_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("execution")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("expert_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("expert_name_id")
                        .HasColumnType("int");

                    b.Property<int?>("factory_id")
                        .HasColumnType("int");

                    b.Property<string>("indicator_category")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("kpi_item_id")
                        .HasColumnType("int");

                    b.Property<string>("number")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("response")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("result_report_id")
                        .HasColumnType("int");

                    b.Property<int?>("result_suggestion_type_id")
                        .HasColumnType("int");

                    b.Property<string>("suggestion_content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("year")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__result_d__3213E83FA4B86494");

                    b.ToTable("result_data");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.result_report", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("factory_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("report_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("report_year")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("id")
                        .HasName("PK__result_r__3213E83F7140F8AF");

                    b.ToTable("result_report");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.result_suggestion_type", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("suggestion_type")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK__result_s__3213E83FCE84C254");

                    b.ToTable("result_suggestion_type");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.set_system", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("code_val")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK__set_syst__3213E83FDFFCAD4D");

                    b.ToTable("set_system");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.suggest_category", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("suggest_category1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("suggest_category");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__suggest___3213E83E1F6751D9");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("id"), false);

                    b.ToTable("suggest_category");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.suggest_item", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("suggest_item1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("suggest_item");

                    b.Property<int?>("suggest_type_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__suggest___3213E83E519D8385");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("id"), false);

                    b.ToTable("suggest_item");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.suggest_type", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("suggest_category_id")
                        .HasColumnType("int");

                    b.Property<string>("suggest_type1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("suggest_type");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__suggest___3213E83EC634A44C");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("id"), false);

                    b.ToTable("suggest_type");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.township_info", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("city_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("township")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__township__3213E83F1A4DF9D1");

                    b.ToTable("township_info");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.user_info", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("anyllmworkspace")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("authority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("enterprise_id")
                        .HasColumnType("int");

                    b.Property<int?>("factory_id")
                        .HasColumnType("int");

                    b.Property<string>("nickname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("username")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id")
                        .HasName("PK__user_inf__3213E83F26124D97");

                    b.ToTable("user_info");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.work_position", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("position")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK__work_pos__3213E83FD1103E86");

                    b.ToTable("work_position");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.credential", b =>
                {
                    b.HasOne("ISHAuditCore.Migrations.user_info", "User")
                        .WithMany("credentials")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__credentia__UserI__0E6E26BF");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISHAuditCore.Migrations.user_info", b =>
                {
                    b.Navigation("credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
